name: 🐛 Bug Report
description: Report a bug or issue with the Humanoid Training Platform
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏
        
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have tested this on the latest version
          required: true
        - label: I have provided all required information below
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "The hand tracking stops working when..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Open the recording screen
        2. Point camera at hands
        3. Start recording
        4. Notice that...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: "Hand tracking should continue working smoothly..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "Hand tracking freezes and shows error..."
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - iOS
        - Android
        - Both
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device Model
      description: What device are you using?
      placeholder: "iPhone 14 Pro, Samsung Galaxy S23, etc."
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What OS version?
      placeholder: "iOS 17.0, Android 13, etc."
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: What version of the app?
      placeholder: "1.2.3"
    validations:
      required: true

  - type: checkboxes
    id: features
    attributes:
      label: Features Involved
      description: Which features are affected?
      options:
        - label: Hand tracking
        - label: Camera recording
        - label: Robot connection
        - label: Marketplace
        - label: 3D mapping
        - label: LIDAR integration
        - label: Data export

  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: How severe is this bug?
      options:
        - Low - Minor inconvenience
        - Medium - Affects functionality but has workaround
        - High - Major functionality broken
        - Critical - App crashes or data loss
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console Logs/Error Messages
      description: Please paste any relevant console logs or error messages
      render: shell
      placeholder: "Paste logs here..."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: "This started happening after updating to iOS 17..." 